### ISSUE TITLE
Parsing problem (OXFException)

### ISSUE THREAD

**Issue by zbodrosk** [52North/series-rest-api#181]
Need help with this:

```
13:43:23.598 [pool-4-thread-1] DEBUG SimpleHttpClient - executing POST method to 'http://sk.ise.cnr.it/observations/sos/kvp'.
13:43:23.992 [DefaultQuartzScheduler_Worker-1] WARN  ConnectorUtils - Error executing capabilities request,  SOS URL: 'http://sk.ise.cnr.it/observations/sos/kvp', SOSAdapter: org.n52.server.da.oxf.SOSAdapter_OXFExtension
org.n52.oxf.OXFException: Could not parse response to XML.
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:302) ~[oxf-sos-adapter-2.0.0-alpha.3.3.jar:2.0.0-alpha.3.3]
	at org.n52.server.da.oxf.SOSAdapter_OXFExtension.doOperation(SOSAdapter_OXFExtension.java:86) ~[sensorwebclient-api-3.3.0-rc.2.jar:na]
	at org.n52.server.da.oxf.SOSAdapter_OXFExtension.initService(SOSAdapter_OXFExtension.java:78) ~[sensorwebclient-api-3.3.0-rc.2.jar:na]
	at org.n52.server.parser.ConnectorUtils$1.call(ConnectorUtils.java:69) ~[sensorwebclient-api-3.3.0-rc.2.jar:na]
	at org.n52.server.parser.ConnectorUtils$1.call(ConnectorUtils.java:1) ~[sensorwebclient-api-3.3.0-rc.2.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_25]
Caused by: org.apache.xmlbeans.XmlException: error: </body> does not close tag <HR>.
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3511) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1277) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1264) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.XmlObject$Factory.parse(XmlObject.java:688) ~[xmlbeans-2.6.0.jar:2.6.0-r1364789]
	at org.n52.oxf.sos.adapter.SOSAdapter.doOperation(SOSAdapter.java:296) ~[oxf-sos-adapter-2.0.0-alpha.3.3.jar:2.0.0-alpha.3.3]
	... 8 common frames omitted
Caused by: org.xml.sax.SAXParseException: </body> does not close tag <HR>.
	at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.reportFatalError(Piccolo.java:1038) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.impl.piccolo.xml.Piccolo.parse(Piccolo.java:723) ~[xmlbeans-2.6.0.jar:na]
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3479) ~[xmlbeans-2.6.0.jar:na]
	... 13 common frames omitted

```

**Comment by EHJ-52n** [comment]
This looks like an server error that results in an HTML page that could not be parsed by XMLbeans.

**Comment by ridoo** [comment]
@zbodrosk @EHJ-52n I think the problem is the KVP endpoint. Please just use `http://sk.ise.cnr.it/observations/sos/soap`, or `http://sk.ise.cnr.it/observations/sos/pox` or `http://sk.ise.cnr.it/observations/sos/service` endpoints (not sure with the last, though)

**Comment by zbodrosk** [comment]
@ridoo @EHJ-52n Sorry for my late reply.
Yes, KVP was the reason for the parsing problem (the same for soap and service). POX do the job. Thank you!

However, there is another problem (maybe to post a new issue?):
```
11:11:53.690 [DefaultQuartzScheduler_Worker-1] TRACE DefaultMetadataHandler - Sending request 1
11:11:53.697 [pool-14-thread-2] DEBUG SimpleHttpClient - executing POST method to 'http://sk.ise.cnr.it/observations/sos/pox'.
11:11:53.891 [pool-14-thread-2] WARN  SOSAdapter_OXFExtension - No converter (http://www.opengis.net/sensorML/1.0.1 -> text/xml; subtype="sensorML/1.0.1") found!
11:11:53.892 [DefaultQuartzScheduler_Worker-1] DEBUG DefaultMetadataHandler - Got NO sensor description for 'http://sp7.irea.cnr.it/sensors/sk.ise.cnr.it/procedure/noManufacturerDeclared/noModelDeclared/noSerialNumberDeclared/20150209123400001'
```

**Comment by ridoo** [comment]
@zbodrosk can't find the location where this happens. Could you please reference it in the code (by adding a link to it) ? Which version of are you using BTW?

**Comment by zbodrosk** [comment]
@ridoo I solved this one. Problem was in SOS version. I wasn't able to edit the last post and inform you about that, sorry.

Can we continue... I have another one, and this time we are close... I think :) 

About you question for the version, I'm using restful-timeseries-webapp-3.3.0-rc.2
There is an error while sending DescribeSensor requests:
```
09:18:49.497 [pool-2-thread-2] DEBUG SimpleHttpClient - executing POST method to 'http://nextdata.get-it.it/observations/sos/pox'.
09:18:50.202 [DefaultQuartzScheduler_Worker-1] WARN  DescribeSensorParser - UOM not found in Describe Sensor Document!
09:18:50.203 [DefaultQuartzScheduler_Worker-1] ERROR DefaultMetadataHandler - Could not find matching phenomenon in internal 'lookup' storage for 'phenomenonTime'
09:18:50.207 [DefaultQuartzScheduler_Worker-1] DEBUG DescribeSensorParser - UOM found: degC
09:18:50.208 [DefaultQuartzScheduler_Worker-1] TRACE DefaultMetadataHandler - Got Procedure data for 'org.n52.shared.serializable.pojos.sos.Procedure [procedureId: 'http://sp7.irea.cnr.it/sensors/nextdata.get-it.it/procedure/GeoPrecisionGmbH/MLog5WCABLE/MAMNORTH/20150510105300001', internalId: 'pro_a48af49f9c6e1d8ec0cf3498acb6ffef', label: '20150510105300001']'.
```

There could be a problem with the data definition, but we couldn't locate it. Please, help.
