### ISSUE TITLE
An exception is thrown if the database contains parameter (parameter table)

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/series-rest-api#245]
If the database contains paramter (parameter table) for the observations the API throws 

> org.hibernate.PropertyAccessException: Exception occurred inside setter of org.n52.series.db.beans.DataEntity.parameters

This issue occurs it the _fetch mode_ is defined as _join_ (fetch="join" in the mapping files) which should be used if there are lots of observations with parameter because _select_ as fetch mode would be to slow (for each observation a select request is send to the database).

Here is the stacktrace:
```
Caused by: org.hibernate.PropertyAccessException: Exception occurred inside setter of org.n52.series.db.beans.DataEntity.parameters
        at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:91) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:713) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:362) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:4718) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:188) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1115) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.processResultSet(Loader.java:973) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.doQuery(Loader.java:921) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2554) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2540) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.Loader.list(Loader.java:2365) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1718) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        at org.n52.series.db.dao.DataDao.getAllInstancesFor(DataDao.java:142) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.db.da.MeasurementDataRepository.assembleData(MeasurementDataRepository.java:111) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.db.da.MeasurementDataRepository.assembleDataWithReferenceValues(MeasurementDataRepository.java:61) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.db.da.MeasurementDataRepository.assembleDataWithReferenceValues(MeasurementDataRepository.java:50) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.db.da.AbstractDataRepository.getData(AbstractDataRepository.java:61) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.srv.TimeseriesAccessService.getDataFor(TimeseriesAccessService.java:81) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.series.srv.TimeseriesAccessService.getData(TimeseriesAccessService.java:65) ~[series-dao-2.0.0-20161013.043211-133.jar:na]
        at org.n52.web.ctrl.TimeseriesDataController.getTimeseriesData(TimeseriesDataController.java:397) ~[rest-2.0.0-20161013.043205-133.jar:na]
        at org.n52.web.ctrl.TimeseriesDataController.getTimeseriesData(TimeseriesDataController.java:139) ~[rest-2.0.0-20161013.043205-133.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) [spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
        ... 73 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor550.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
        at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:68) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
        ... 109 common frames omitted
```

**Comment by ridoo** [comment]
Hmm, this actually worked before ... the `parameter` inheritance model must have changed within SOS v4.4.x database schema .. I'll check this

**Comment by ridoo** [comment]
I can reproduce this error when parent entities in the `parameter` table do have no referenced entity in one of the corresponding subclass-tables (as there is `inheritance-per-subclass`). As `ParameterEntity` is `abstract` and no concrete class can be determined, it can't instantiate an instance of the given row.

IMHO it is a data integrity problem and the SOS should throw the same exception when a `GetObservation` touches observations having parameters with no actual value reference entity.

To verify, I removed the `abstract` keyword from `DataParameter` and the `datasets/{id}/data` output contained a `null`. But this is not what we intend to output here, right .. Could you double check, if there is a parameter value entity available in one of the corresponding subclass tables?

I see two possilble solutions:
1. Tell Hibernate to ignore _incomplete_ entities in `table-per-subclass` inheritance. Do you know how to tell Hibernate to only join available subclass entities in this case? (actually a simple `right join` should do the trick, but it seems not being as easy as putting `force=true` in the `discriminator` in `single-table-inheritance`). 
2. Enhance data model to not allow _incomplete_ entities in `table-per-subclass` inheritance. My feeling is this makes more sense to not allow such cases in the data model

However, perhaps you may have a better solution at hand. Let me know what you think.

**Comment by ridoo** [comment]
@CarstenHollmann have you double checked if your parameters available all have data in the corresponding `subclass`-table which could be joined by Hibernate?

My current work had to do with parameters data available in `Parameter` table, and the exception you observed did not appear. Feel free to close this issue, if not relevant anymore

**Comment by ridoo** [comment]
closing
